# ═══════════════════════════════════════════════════════════
# Aura-Sentinel  |  AUTO-GENERATED REMEDIATION CONFIG
# Generated  : 2026-03-28T11:15:02.999515+00:00
# Threat IPs : 1 C2 hub(s) identified
# DO NOT EDIT manually — managed by remediation_agent.py
# ═══════════════════════════════════════════════════════════

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS region to deploy firewall rules"
  type        = string
  default     = "us-east-1"
}

resource "aws_networkfirewall_rule_group" "aura_sentinel_block_c2" {
  capacity = 100
  name     = "aura-sentinel-c2-block-20260328111502"
  type     = "STATEFUL"
  description = "Auto-generated by Aura-Sentinel Reaper Agent"

  rule_group {
    rules_source {
      rules_string = <<-EOT
drop ip any any -> 192.168.100.50 any (msg:"AURA-SENTINEL C2 block 192.168.100.50"; sid:10000; rev:1;)
      EOT
    }
    stateful_rule_options {
      rule_order = "STRICT_ORDER"
    }
  }

  tags = {
    ManagedBy   = "aura-sentinel"
    GeneratedAt = "2026-03-28T11:15:02.999534+00:00"
    ThreatClass = "C2-Botnet-Hub"
  }
}

resource "aws_networkfirewall_firewall_policy" "aura_sentinel_policy" {
  name = "aura-sentinel-policy-20260328111502"

  firewall_policy {
    stateless_default_actions          = ["aws:forward_to_sfe"]
    stateless_fragment_default_actions = ["aws:forward_to_sfe"]

    stateful_rule_group_reference {
      priority     = 1
      resource_arn = aws_networkfirewall_rule_group.aura_sentinel_block_c2.arn
    }
  }

  tags = {
    ManagedBy = "aura-sentinel"
  }
}

output "blocked_ips" {
  description = "IPs null-routed by this deployment"
  value       = aws_networkfirewall_rule_group.aura_sentinel_block_c2.name
}

output "policy_arn" {
  description = "ARN of the enforced firewall policy"
  value       = aws_networkfirewall_firewall_policy.aura_sentinel_policy.arn
}
