apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aura-sentinel

resources:
  - namespace.yaml
  - secrets.yaml
  - zookeeper.yaml
  - kafka.yaml
  - neo4j.yaml
  - consumers.yaml
  - prometheus-grafana.yaml

configMapGenerator:
  - name: grafana-aura-dashboard
    files:
      - aura_sentinel.json=grafana/dashboards/aura_sentinel.json
